#!/home/train/miniconda3/bin/python
# -*- coding: utf-8 -*-
# Created Time  : 2023/08/29 17:19
# Author        : William GoGo
"""
读取 de_results_add_def.py 生成的 DEG_data.txt 文件
把 regulation 变为 1,0,-1 对应 up,nosig,down
生成的文件只包括 K_ID 和 regulation
例如：K12345    0
一个 K_ID 对应多个 GeneID，有可能 up,down,nosig 都有
对 K_ID 去重，哪个 regulation 多留下哪个，一样多的变为 0
并生成一个中间文件，方便检查
"""
import os
import pandas as pd
import argparse


passed_path = [
    ['ko00010', 'Glycolysis_Gluconeogenesis'],
    ['ko00020', 'Citrate_cycle_TCA_cycle'],
    ['ko00030', 'Pentose_phosphate_pathway'],
    ['ko00040', 'Pentose_and_glucuronate_interconversions'],
    ['ko00051', 'Fructose_and_mannose_metabolism'],
    ['ko00052', 'Galactose_metabolism'],
    ['ko00053', 'Ascorbate_and_aldarate_metabolism'],
    ['ko00061', 'Fatty_acid_biosynthesis'],
    ['ko00062', 'Fatty_acid_elongation'],
    ['ko00071', 'Fatty_acid_degradation'],
    ['ko00073', 'Cutin_suberine_and_wax_biosynthesis'],
    ['ko00100', 'Steroid_biosynthesis'],
    ['ko00120', 'Primary_bile_acid_biosynthesis'],
    ['ko00130', 'Ubiquinone_and_other_terpenoid_quinone_biosynthesis'],
    ['ko00140', 'Steroid_hormone_biosynthesis'],
    ['ko00190', 'Oxidative_phosphorylation'],
    ['ko00195', 'Photosynthesis'],
    ['ko00196', 'Photosynthesis_antenna_proteins'],
    ['ko00220', 'Arginine_biosynthesis'],
    ['ko00230', 'Purine_metabolism'],
    ['ko00232', 'Caffeine_metabolism'],
    ['ko00240', 'Pyrimidine_metabolism'],
    ['ko00250', 'Alanine_aspartate_and_glutamate_metabolism'],
    ['ko00253', 'Tetracycline_biosynthesis'],
    ['ko00254', 'Aflatoxin_biosynthesis'],
    ['ko00260', 'Glycine_serine_and_threonine_metabolism'],
    ['ko00261', 'Monobactam_biosynthesis'],
    ['ko00270', 'Cysteine_and_methionine_metabolism'],
    ['ko00280', 'Valine_leucine_and_isoleucine_degradation'],
    ['ko00290', 'Valine_leucine_and_isoleucine_biosynthesis'],
    ['ko00300', 'Lysine_biosynthesis'],
    ['ko00310', 'Lysine_degradation'],
    ['ko00311', 'Penicillin_and_cephalosporin_biosynthesis'],
    ['ko00330', 'Arginine_and_proline_metabolism'],
    ['ko00331', 'Clavulanic_acid_biosynthesis'],
    ['ko00332', 'Carbapenem_biosynthesis'],
    ['ko00333', 'Prodigiosin_biosynthesis'],
    ['ko00340', 'Histidine_metabolism'],
    ['ko00350', 'Tyrosine_metabolism'],
    ['ko00360', 'Phenylalanine_metabolism'],
    ['ko00361', 'Chlorocyclohexane_and_chlorobenzene_degradation'],
    ['ko00362', 'Benzoate_degradation'],
    ['ko00363', 'Bisphenol_degradation'],
    ['ko00364', 'Fluorobenzoate_degradation'],
    ['ko00365', 'Furfural_degradation'],
    ['ko00380', 'Tryptophan_metabolism'],
    ['ko00400', 'Phenylalanine_tyrosine_and_tryptophan_biosynthesis'],
    ['ko00401', 'Novobiocin_biosynthesis'],
    ['ko00402', 'Benzoxazinoid_biosynthesis'],
    ['ko00403', 'Indole_diterpene_alkaloid_biosynthesis'],
    ['ko00404', 'Staurosporine_biosynthesis'],
    ['ko00405', 'Phenazine_biosynthesis'],
    ['ko00410', 'beta_Alanine_metabolism'],
    ['ko00430', 'Taurine_and_hypotaurine_metabolism'],
    ['ko00440', 'Phosphonate_and_phosphinate_metabolism'],
    ['ko00450', 'Selenocompound_metabolism'],
    ['ko00460', 'Cyanoamino_acid_metabolism'],
    ['ko00480', 'Glutathione_metabolism'],
    ['ko00500', 'Starch_and_sucrose_metabolism'],
    ['ko00510', 'N_Glycan_biosynthesis'],
    ['ko00512', 'Mucin_type_O_glycan_biosynthesis'],
    ['ko00513', 'Various_types_of_N_glycan_biosynthesis'],
    ['ko00515', 'Mannose_type_O_glycan_biosynthesis'],
    ['ko00520', 'Amino_sugar_and_nucleotide_sugar_metabolism'],
    ['ko00521', 'Streptomycin_biosynthesis'],
    ['ko00522', 'Biosynthesis_of_12_14_and_16_membered_macrolides'],
    ['ko00523', 'Polyketide_sugar_unit_biosynthesis'],
    ['ko00524', 'Neomycin_kanamycin_and_gentamicin_biosynthesis'],
    ['ko00525', 'Acarbose_and_validamycin_biosynthesis'],
    ['ko00531', 'Glycosaminoglycan_degradation'],
    ['ko00532', 'Glycosaminoglycan_biosynthesis_chondroitin_sulfate_dermatan_sulfate'],
    ['ko00534', 'Glycosaminoglycan_biosynthesis_heparan_sulfate_heparin'],
    ['ko00540', 'Lipopolysaccharide_biosynthesis'],
    ['ko00541', 'O_Antigen_nucleotide_sugar_biosynthesis'],
    ['ko00550', 'Peptidoglycan_biosynthesis'],
    ['ko00561', 'Glycerolipid_metabolism'],
    ['ko00562', 'Inositol_phosphate_metabolism'],
    ['ko00563', 'Glycosylphosphatidylinositol_GPI_anchor_biosynthesis'],
    ['ko00564', 'Glycerophospholipid_metabolism'],
    ['ko00565', 'Ether_lipid_metabolism'],
    ['ko00571', 'Lipoarabinomannan_LAM_biosynthesis'],
    ['ko00572', 'Arabinogalactan_biosynthesis_Mycobacterium'],
    ['ko00590', 'Arachidonic_acid_metabolism'],
    ['ko00591', 'Linoleic_acid_metabolism'],
    ['ko00592', 'alpha_Linolenic_acid_metabolism'],
    ['ko00600', 'Sphingolipid_metabolism'],
    ['ko00601', 'Glycosphingolipid_biosynthesis_lacto_and_neolacto_series'],
    ['ko00603', 'Glycosphingolipid_biosynthesis_globo_and_isoglobo_series'],
    ['ko00604', 'Glycosphingolipid_biosynthesis_ganglio_series'],
    ['ko00620', 'Pyruvate_metabolism'],
    ['ko00621', 'Dioxin_degradation'],
    ['ko00622', 'Xylene_degradation'],
    ['ko00623', 'Toluene_degradation'],
    ['ko00624', 'Polycyclic_aromatic_hydrocarbon_degradation'],
    ['ko00625', 'Chloroalkane_and_chloroalkene_degradation'],
    ['ko00626', 'Naphthalene_degradation'],
    ['ko00627', 'Aminobenzoate_degradation'],
    ['ko00630', 'Glyoxylate_and_dicarboxylate_metabolism'],
    ['ko00633', 'Nitrotoluene_degradation'],
    ['ko00640', 'Propanoate_metabolism'],
    ['ko00642', 'Ethylbenzene_degradation'],
    ['ko00643', 'Styrene_degradation'],
    ['ko00650', 'Butanoate_metabolism'],
    ['ko00660', 'C5_Branched_dibasic_acid_metabolism'],
    ['ko00670', 'One_carbon_pool_by_folate'],
    ['ko00680', 'Methane_metabolism'],
    ['ko00710', 'Carbon_fixation_in_photosynthetic_organisms'],
    ['ko00720', 'Carbon_fixation_pathways_in_prokaryotes'],
    ['ko00730', 'Thiamine_metabolism'],
    ['ko00740', 'Riboflavin_metabolism'],
    ['ko00750', 'Vitamin_B6_metabolism'],
    ['ko00760', 'Nicotinate_and_nicotinamide_metabolism'],
    ['ko00770', 'Pantothenate_and_CoA_biosynthesis'],
    ['ko00780', 'Biotin_metabolism'],
    ['ko00785', 'Lipoic_acid_metabolism'],
    ['ko00790', 'Folate_biosynthesis'],
    ['ko00791', 'Atrazine_degradation'],
    ['ko00830', 'Retinol_metabolism'],
    ['ko00860', 'Porphyrin_and_chlorophyll_metabolism'],
    ['ko00900', 'Terpenoid_backbone_biosynthesis'],
    ['ko00901', 'Indole_alkaloid_biosynthesis'],
    ['ko00902', 'Monoterpenoid_biosynthesis'],
    ['ko00903', 'Limonene_and_pinene_degradation'],
    ['ko00904', 'Diterpenoid_biosynthesis'],
    ['ko00905', 'Brassinosteroid_biosynthesis'],
    ['ko00906', 'Carotenoid_biosynthesis'],
    ['ko00908', 'Zeatin_biosynthesis'],
    ['ko00909', 'Sesquiterpenoid_and_triterpenoid_biosynthesis'],
    ['ko00910', 'Nitrogen_metabolism'],
    ['ko00920', 'Sulfur_metabolism'],
    ['ko00930', 'Caprolactam_degradation'],
    ['ko00940', 'Phenylpropanoid_biosynthesis'],
    ['ko00941', 'Flavonoid_biosynthesis'],
    ['ko00942', 'Anthocyanin_biosynthesis'],
    ['ko00943', 'Isoflavonoid_biosynthesis'],
    ['ko00944', 'Flavone_and_flavonol_biosynthesis'],
    ['ko00945', 'Stilbenoid_diarylheptanoid_and_gingerol_biosynthesis'],
    ['ko00950', 'Isoquinoline_alkaloid_biosynthesis'],
    ['ko00960', 'Tropane_piperidine_and_pyridine_alkaloid_biosynthesis'],
    ['ko00965', 'Betalain_biosynthesis'],
    ['ko00966', 'Glucosinolate_biosynthesis'],
    ['ko00970', 'Aminoacyl_tRNA_biosynthesis'],
    ['ko00980', 'Metabolism_of_xenobiotics_by_cytochrome_P450'],
    ['ko00981', 'Insect_hormone_biosynthesis'],
    ['ko00982', 'Drug_metabolism_cytochrome_P450'],
    ['ko00983', 'Drug_metabolism_other_enzymes'],
    ['ko00984', 'Steroid_degradation'],
    ['ko00997', 'Biosynthesis_of_various_secondary_metabolites_part_3'],
    ['ko00998', 'Biosynthesis_of_various_secondary_metabolites_part_2'],
    ['ko00999', 'Biosynthesis_of_various_secondary_metabolites_part_1'],
    ['ko01040', 'Biosynthesis_of_unsaturated_fatty_acids'],
    ['ko01051', 'Biosynthesis_of_ansamycins'],
    ['ko01052', 'Type_I_polyketide_structures'],
    ['ko01053', 'Biosynthesis_of_siderophore_group_nonribosomal_peptides'],
    ['ko01055', 'Biosynthesis_of_vancomycin_group_antibiotics'],
    ['ko01056', 'Biosynthesis_of_type_II_polyketide_backbone'],
    ['ko01057', 'Biosynthesis_of_type_II_polyketide_products'],
    ['ko01059', 'Biosynthesis_of_enediyne_antibiotics'],
    ['ko01501', 'beta_Lactam_resistance'],
    ['ko01502', 'Vancomycin_resistance'],
    ['ko01503', 'Cationic_antimicrobial_peptide_CAMP_resistance'],
    ['ko01521', 'EGFR_tyrosine_kinase_inhibitor_resistance'],
    ['ko01522', 'Endocrine_resistance'],
    ['ko01523', 'Antifolate_resistance'],
    ['ko01524', 'Platinum_drug_resistance'],
    ['ko02010', 'ABC_transporters'],
    ['ko02020', 'Two_component_system'],
    ['ko02024', 'Quorum_sensing'],
    ['ko02025', 'Biofilm_formation_Pseudomonas_aeruginosa'],
    ['ko02026', 'Biofilm_formation_Escherichia_coli'],
    ['ko02030', 'Bacterial_chemotaxis'],
    ['ko02040', 'Flagellar_assembly'],
    ['ko02060', 'Phosphotransferase_system_PTS'],
    ['ko03008', 'Ribosome_biogenesis_in_eukaryotes'],
    ['ko03010', 'Ribosome'],
    ['ko03013', 'RNA_transport'],
    ['ko03015', 'mRNA_surveillance_pathway'],
    ['ko03018', 'RNA_degradation'],
    ['ko03020', 'RNA_polymerase'],
    ['ko03022', 'Basal_transcription_factors'],
    ['ko03030', 'DNA_replication'],
    ['ko03040', 'Spliceosome'],
    ['ko03050', 'Proteasome'],
    ['ko03060', 'Protein_export'],
    ['ko03070', 'Bacterial_secretion_system'],
    ['ko03320', 'PPAR_signaling_pathway'],
    ['ko03410', 'Base_excision_repair'],
    ['ko03420', 'Nucleotide_excision_repair'],
    ['ko03430', 'Mismatch_repair'],
    ['ko03440', 'Homologous_recombination'],
    ['ko03450', 'Non_homologous_end_joining'],
    ['ko03460', 'Fanconi_anemia_pathway'],
    ['ko04010', 'MAPK_signaling_pathway'],
    ['ko04011', 'MAPK_signaling_pathway_yeast'],
    ['ko04012', 'ErbB_signaling_pathway'],
    ['ko04013', 'MAPK_signaling_pathway_fly'],
    ['ko04014', 'Ras_signaling_pathway'],
    ['ko04015', 'Rap1_signaling_pathway'],
    ['ko04016', 'MAPK_signaling_pathway_plant'],
    ['ko04020', 'Calcium_signaling_pathway'],
    ['ko04022', 'cGMP_PKG_signaling_pathway'],
    ['ko04024', 'cAMP_signaling_pathway'],
    ['ko04060', 'Cytokine_cytokine_receptor_interaction'],
    ['ko04061', 'Viral_protein_interaction_with_cytokine_and_cytokine_receptor'],
    ['ko04062', 'Chemokine_signaling_pathway'],
    ['ko04064', 'NF_kappa_B_signaling_pathway'],
    ['ko04066', 'HIF_1_signaling_pathway'],
    ['ko04068', 'FoxO_signaling_pathway'],
    ['ko04070', 'Phosphatidylinositol_signaling_system'],
    ['ko04071', 'Sphingolipid_signaling_pathway'],
    ['ko04072', 'Phospholipase_D_signaling_pathway'],
    ['ko04075', 'Plant_hormone_signal_transduction'],
    ['ko04080', 'Neuroactive_ligand_receptor_interaction'],
    ['ko04110', 'Cell_cycle'],
    ['ko04111', 'Cell_cycle_yeast'],
    ['ko04112', 'Cell_cycle_Caulobacter'],
    ['ko04113', 'Meiosis_yeast'],
    ['ko04114', 'Oocyte_meiosis'],
    ['ko04115', 'p53_signaling_pathway'],
    ['ko04120', 'Ubiquitin_mediated_proteolysis'],
    ['ko04122', 'Sulfur_relay_system'],
    ['ko04130', 'SNARE_interactions_in_vesicular_transport'],
    ['ko04136', 'Autophagy_other'],
    ['ko04137', 'Mitophagy_animal'],
    ['ko04138', 'Autophagy_yeast'],
    ['ko04139', 'Mitophagy_yeast'],
    ['ko04140', 'Autophagy_animal'],
    ['ko04141', 'Protein_processing_in_endoplasmic_reticulum'],
    ['ko04142', 'Lysosome'],
    ['ko04144', 'Endocytosis'],
    ['ko04145', 'Phagosome'],
    ['ko04146', 'Peroxisome'],
    ['ko04150', 'mTOR_signaling_pathway'],
    ['ko04151', 'PI3K_Akt_signaling_pathway'],
    ['ko04152', 'AMPK_signaling_pathway'],
    ['ko04210', 'Apoptosis'],
    ['ko04211', 'Longevity_regulating_pathway'],
    ['ko04212', 'Longevity_regulating_pathway_worm'],
    ['ko04213', 'Longevity_regulating_pathway_multiple_species'],
    ['ko04214', 'Apoptosis_fly'],
    ['ko04216', 'Ferroptosis'],
    ['ko04217', 'Necroptosis'],
    ['ko04218', 'Cellular_senescence'],
    ['ko04260', 'Cardiac_muscle_contraction'],
    ['ko04261', 'Adrenergic_signaling_in_cardiomyocytes'],
    ['ko04270', 'Vascular_smooth_muscle_contraction'],
    ['ko04310', 'Wnt_signaling_pathway'],
    ['ko04320', 'Dorso_ventral_axis_formation'],
    ['ko04330', 'Notch_signaling_pathway'],
    ['ko04340', 'Hedgehog_signaling_pathway'],
    ['ko04341', 'Hedgehog_signaling_pathway_fly'],
    ['ko04350', 'TGF_beta_signaling_pathway'],
    ['ko04360', 'Axon_guidance'],
    ['ko04361', 'Axon_regeneration'],
    ['ko04370', 'VEGF_signaling_pathway'],
    ['ko04371', 'Apelin_signaling_pathway'],
    ['ko04380', 'Osteoclast_differentiation'],
    ['ko04390', 'Hippo_signaling_pathway'],
    ['ko04391', 'Hippo_signaling_pathway_fly'],
    ['ko04392', 'Hippo_signaling_pathway_multiple_species'],
    ['ko04510', 'Focal_adhesion'],
    ['ko04512', 'ECM_receptor_interaction'],
    ['ko04514', 'Cell_adhesion_molecules'],
    ['ko04520', 'Adherens_junction'],
    ['ko04530', 'Tight_junction'],
    ['ko04540', 'Gap_junction'],
    ['ko04550', 'Signaling_pathways_regulating_pluripotency_of_stem_cells'],
    ['ko04610', 'Complement_and_coagulation_cascades'],
    ['ko04611', 'Platelet_activation'],
    ['ko04612', 'Antigen_processing_and_presentation'],
    ['ko04613', 'Neutrophil_extracellular_trap_formation'],
    ['ko04614', 'Renin_angiotensin_system'],
    ['ko04620', 'Toll_like_receptor_signaling_pathway'],
    ['ko04621', 'NOD_like_receptor_signaling_pathway'],
    ['ko04622', 'RIG_I_like_receptor_signaling_pathway'],
    ['ko04623', 'Cytosolic_DNA_sensing_pathway'],
    ['ko04624', 'Toll_and_Imd_signaling_pathway'],
    ['ko04625', 'C_type_lectin_receptor_signaling_pathway'],
    ['ko04626', 'Plant_pathogen_interaction'],
    ['ko04630', 'JAK_STAT_signaling_pathway'],
    ['ko04640', 'Hematopoietic_cell_lineage'],
    ['ko04650', 'Natural_killer_cell_mediated_cytotoxicity'],
    ['ko04657', 'IL_17_signaling_pathway'],
    ['ko04658', 'Th1_and_Th2_cell_differentiation'],
    ['ko04659', 'Th17_cell_differentiation'],
    ['ko04660', 'T_cell_receptor_signaling_pathway'],
    ['ko04662', 'B_cell_receptor_signaling_pathway'],
    ['ko04664', 'Fc_epsilon_RI_signaling_pathway'],
    ['ko04666', 'Fc_gamma_R_mediated_phagocytosis'],
    ['ko04668', 'TNF_signaling_pathway'],
    ['ko04670', 'Leukocyte_transendothelial_migration'],
    ['ko04672', 'Intestinal_immune_network_for_IgA_production'],
    ['ko04710', 'Circadian_rhythm'],
    ['ko04711', 'Circadian_rhythm_fly'],
    ['ko04712', 'Circadian_rhythm_plant'],
    ['ko04713', 'Circadian_entrainment'],
    ['ko04714', 'Thermogenesis'],
    ['ko04720', 'Long_term_potentiation'],
    ['ko04721', 'Synaptic_vesicle_cycle'],
    ['ko04722', 'Neurotrophin_signaling_pathway'],
    ['ko04724', 'Glutamatergic_synapse'],
    ['ko04725', 'Cholinergic_synapse'],
    ['ko04726', 'Serotonergic_synapse'],
    ['ko04727', 'GABAergic_synapse'],
    ['ko04728', 'Dopaminergic_synapse'],
    ['ko04730', 'Long_term_depression'],
    ['ko04740', 'Olfactory_transduction'],
    ['ko04742', 'Taste_transduction'],
    ['ko04744', 'Phototransduction'],
    ['ko04745', 'Phototransduction_fly'],
    ['ko04750', 'Inflammatory_mediator_regulation_of_TRP_channels'],
    ['ko04810', 'Regulation_of_actin_cytoskeleton'],
    ['ko04910', 'Insulin_signaling_pathway'],
    ['ko04911', 'Insulin_secretion'],
    ['ko04912', 'GnRH_signaling_pathway'],
    ['ko04913', 'Ovarian_steroidogenesis'],
    ['ko04914', 'Progesterone_mediated_oocyte_maturation'],
    ['ko04915', 'Estrogen_signaling_pathway'],
    ['ko04916', 'Melanogenesis'],
    ['ko04917', 'Prolactin_signaling_pathway'],
    ['ko04918', 'Thyroid_hormone_synthesis'],
    ['ko04919', 'Thyroid_hormone_signaling_pathway'],
    ['ko04920', 'Adipocytokine_signaling_pathway'],
    ['ko04921', 'Oxytocin_signaling_pathway'],
    ['ko04922', 'Glucagon_signaling_pathway'],
    ['ko04923', 'Regulation_of_lipolysis_in_adipocytes'],
    ['ko04924', 'Renin_secretion'],
    ['ko04925', 'Aldosterone_synthesis_and_secretion'],
    ['ko04926', 'Relaxin_signaling_pathway'],
    ['ko04927', 'Cortisol_synthesis_and_secretion'],
    ['ko04928', 'Parathyroid_hormone_synthesis_secretion_and_action'],
    ['ko04929', 'GnRH_secretion'],
    ['ko04930', 'Type_II_diabetes_mellitus'],
    ['ko04931', 'Insulin_resistance'],
    ['ko04932', 'Non_alcoholic_fatty_liver_disease'],
    ['ko04933', 'AGE_RAGE_signaling_pathway_in_diabetic_complications'],
    ['ko04934', 'Cushing_syndrome'],
    ['ko04935', 'Growth_hormone_synthesis_secretion_and_action'],
    ['ko04940', 'Type_I_diabetes_mellitus'],
    ['ko04950', 'Maturity_onset_diabetes_of_the_young'],
    ['ko04960', 'Aldosterone_regulated_sodium_reabsorption'],
    ['ko04961', 'Endocrine_and_other_factor_regulated_calcium_reabsorption'],
    ['ko04962', 'Vasopressin_regulated_water_reabsorption'],
    ['ko04964', 'Proximal_tubule_bicarbonate_reclamation'],
    ['ko04966', 'Collecting_duct_acid_secretion'],
    ['ko04970', 'Salivary_secretion'],
    ['ko04971', 'Gastric_acid_secretion'],
    ['ko04972', 'Pancreatic_secretion'],
    ['ko04973', 'Carbohydrate_digestion_and_absorption'],
    ['ko04974', 'Protein_digestion_and_absorption'],
    ['ko04975', 'Fat_digestion_and_absorption'],
    ['ko04976', 'Bile_secretion'],
    ['ko04977', 'Vitamin_digestion_and_absorption'],
    ['ko04978', 'Mineral_absorption'],
    ['ko04979', 'Cholesterol_metabolism'],
    ['ko05010', 'Alzheimer_disease'],
    ['ko05012', 'Parkinson_disease'],
    ['ko05014', 'Amyotrophic_lateral_sclerosis'],
    ['ko05016', 'Huntington_disease'],
    ['ko05017', 'Spinocerebellar_ataxia'],
    ['ko05020', 'Prion_disease'],
    ['ko05022', 'Pathways_of_neurodegeneration_multiple_diseases'],
    ['ko05030', 'Cocaine_addiction'],
    ['ko05031', 'Amphetamine_addiction'],
    ['ko05032', 'Morphine_addiction'],
    ['ko05033', 'Nicotine_addiction'],
    ['ko05034', 'Alcoholism'],
    ['ko05100', 'Bacterial_invasion_of_epithelial_cells'],
    ['ko05110', 'Vibrio_cholerae_infection'],
    ['ko05111', 'Biofilm_formation_Vibrio_cholerae'],
    ['ko05120', 'Epithelial_cell_signaling_in_Helicobacter_pylori_infection'],
    ['ko05130', 'Pathogenic_Escherichia_coli_infection'],
    ['ko05131', 'Shigellosis'],
    ['ko05132', 'Salmonella_infection'],
    ['ko05133', 'Pertussis'],
    ['ko05134', 'Legionellosis'],
    ['ko05135', 'Yersinia_infection'],
    ['ko05140', 'Leishmaniasis'],
    ['ko05142', 'Chagas_disease'],
    ['ko05143', 'African_trypanosomiasis'],
    ['ko05144', 'Malaria'],
    ['ko05145', 'Toxoplasmosis'],
    ['ko05146', 'Amoebiasis'],
    ['ko05150', 'Staphylococcus_aureus_infection'],
    ['ko05152', 'Tuberculosis'],
    ['ko05160', 'Hepatitis_C'],
    ['ko05161', 'Hepatitis_B'],
    ['ko05162', 'Measles'],
    ['ko05163', 'Human_cytomegalovirus_infection'],
    ['ko05164', 'Influenza_A'],
    ['ko05165', 'Human_papillomavirus_infection'],
    ['ko05166', 'Human_T_cell_leukemia_virus_1_infection'],
    ['ko05167', 'Kaposi_sarcoma_associated_herpesvirus_infection'],
    ['ko05168', 'Herpes_simplex_virus_1_infection'],
    ['ko05169', 'Epstein_Barr_virus_infection'],
    ['ko05170', 'Human_immunodeficiency_virus_1_infection'],
    ['ko05171', 'Coronavirus_disease_COVID_19'],
    ['ko05200', 'Pathways_in_cancer'],
    ['ko05202', 'Transcriptional_misregulation_in_cancer'],
    ['ko05203', 'Viral_carcinogenesis'],
    ['ko05204', 'Chemical_carcinogenesis'],
    ['ko05205', 'Proteoglycans_in_cancer'],
    ['ko05210', 'Colorectal_cancer'],
    ['ko05211', 'Renal_cell_carcinoma'],
    ['ko05212', 'Pancreatic_cancer'],
    ['ko05213', 'Endometrial_cancer'],
    ['ko05214', 'Glioma'],
    ['ko05215', 'Prostate_cancer'],
    ['ko05216', 'Thyroid_cancer'],
    ['ko05217', 'Basal_cell_carcinoma'],
    ['ko05218', 'Melanoma'],
    ['ko05219', 'Bladder_cancer'],
    ['ko05220', 'Chronic_myeloid_leukemia'],
    ['ko05221', 'Acute_myeloid_leukemia'],
    ['ko05222', 'Small_cell_lung_cancer'],
    ['ko05223', 'Non_small_cell_lung_cancer'],
    ['ko05224', 'Breast_cancer'],
    ['ko05225', 'Hepatocellular_carcinoma'],
    ['ko05226', 'Gastric_cancer'],
    ['ko05230', 'Central_carbon_metabolism_in_cancer'],
    ['ko05231', 'Choline_metabolism_in_cancer'],
    ['ko05235', 'PD_L1_expression_and_PD_1_checkpoint_pathway_in_cancer'],
    ['ko05310', 'Asthma'],
    ['ko05320', 'Autoimmune_thyroid_disease'],
    ['ko05321', 'Inflammatory_bowel_disease'],
    ['ko05322', 'Systemic_lupus_erythematosus'],
    ['ko05323', 'Rheumatoid_arthritis'],
    ['ko05330', 'Allograft_rejection'],
    ['ko05332', 'Graft_versus_host_disease'],
    ['ko05340', 'Primary_immunodeficiency'],
    ['ko05410', 'Hypertrophic_cardiomyopathy'],
    ['ko05412', 'Arrhythmogenic_right_ventricular_cardiomyopathy'],
    ['ko05414', 'Dilated_cardiomyopathy'],
    ['ko05416', 'Viral_myocarditis'],
    ['ko05418', 'Fluid_shear_stress_and_atherosclerosis']
]

kegg_passed_pathway_df = pd.DataFrame(passed_path, columns=['ko_number', 'Des'])

def parse_input():
    argparser = argparse.ArgumentParser(description='读取 de_results_add_def.py 生成的文件')
    argparser.add_argument('-u', '--up-id', dest='up_idlist', type=str, required=True, 
                           help='输入 Up ID list')
    argparser.add_argument('-d', '--down-id', dest='down_idlist', type=str, required=True, 
                           help='输入 Down ID list')
    argparser.add_argument('-o', '--output', dest='output_file', type=str, required=True,
                           help='输出文件')
    argparser.add_argument('-p', '--pathway', dest='pathway', type=str, required=True,
                           help='输入 kegg_path 文件，需要画的 kegg_path，处理掉一些不能画的图，并替换原文件')
    argparser.add_argument('--kegg-clean', dest='kegg_clean', type=str, required=True,
                           help="输入 kegg 注释出来的 'KEGG_clean 文件'")
    return argparser.parse_args()


def kid_optmial(input_df):
    id_list = input_df.to_dict(orient='split')['data']
    dic = {}
    result_dic = {}
    for id in id_list:
        dic[id[0]] = {'up': 0, 'down': 0, 'nosig': 0}

    for each_line in id_list:
        id = each_line[0]
        reg = each_line[1]
        if str(reg) == '1':
            dic[id]['up'] += 1
        elif str(reg) == '0':
            dic[id]['nosig'] += 1
        elif str(reg) == '-1':
            dic[id]['down'] += 1

    for each_kid, kid_values in dic.items():
        if kid_values['up'] > kid_values['down']:
            result_dic[each_kid] = 1
        elif kid_values['up'] < kid_values['down']:
            result_dic[each_kid] = -1
        elif kid_values['up'] == kid_values['down']:
            result_dic[each_kid] = 0

    return result_dic
            

def up_down_idlist_geneid2kid(input_file_down, input_file_up, output_file, kegg_clean):
    kegg_clean_df = pd.read_csv(kegg_clean, sep='\t', usecols=[0, 4], names=['GeneID', 'KEGG_ID'])
    
    down_df = pd.read_csv(input_file_down, sep='\t', names=['GeneID'])
    down_df = pd.merge(left=down_df, right=kegg_clean_df, on='GeneID', how='left')
    down_df = down_df.drop_duplicates(subset='GeneID', keep='first')
    down_df = down_df.dropna().drop(columns=['GeneID'])
    down_df['regulation'] = -1

    up_df = pd.read_csv(input_file_up, sep='\t', names=['GeneID'])
    up_df = pd.merge(left=up_df, right=kegg_clean_df, on='GeneID', how='left')
    up_df = up_df.drop_duplicates(subset='GeneID', keep='first')
    up_df = up_df.dropna().drop(columns=['GeneID'])
    up_df['regulation'] = 1
    
    df = pd.concat([down_df, up_df])
    result_dic = kid_optmial(df)
    
    with open(output_file, 'w') as f:
        f.write(f'KEGG_ID\tregulation\n')
        for each_kid, kid_values in result_dic.items():
            f.write(f'{each_kid}\t{kid_values}\n')


def kegg_pathway_filter(kegg_file):
    kegg_file_df = pd.read_csv(kegg_file, sep='\t', names=['ko_number', 'Des'])
    result_df = kegg_file_df[kegg_file_df['ko_number'].isin(kegg_passed_pathway_df['ko_number'])]
    result_df.to_csv(kegg_file, sep='\t', index=False, header=False)


def main():
    args = parse_input()
    up_down_idlist_geneid2kid(args.down_idlist, args.up_idlist, args.output_file, args.kegg_clean)
    kegg_pathway_filter(args.pathway)
    

if __name__ == "__main__":
    main()